In [1]:
import pandas as pd 
import numpy as np 


In [67]:
A = pd.read_csv("test.csv", sep=",", header = None).to_numpy()

In [68]:
valid(A)

[[-1  1  0  1]
 [ 2 -1  2  0]
 [ 0  1 -1  1]
 [ 2  0  2 -1]]
1 loops found!
f(2, 0) = f(0, 2)
1 loops found!
f(3, 1) = f(1, 3)
1 loops found!
f(0, 2) = f(2, 0)
1 loops found!
f(1, 3) = f(3, 1)


In [66]:
def valid(A):
    print(A)
    size = A.shape[0]
    if(A.shape[0]!=A.shape[1]):
        print("A is not a square matrix!")
        return
    for y in range(size):
        for x in range(size):
            if x==y: continue
            collisions = np.where(A[:, y]==A[y, x])[0]
            if collisions.shape[0] !=0 :
                print(f"{collisions.shape[0]} loops found!")
                for x2 in collisions:
                    print(f'f({x}, {y}) = f({y}, {x2})')

In [52]:
np.where(A[:,1]==-1)[0].shape[0]

0